### ISSUE TITLE
IllegalStateException: The specified child already has a parent. 

### ISSUE THREAD

**Issue by ItsCalebJones** [michael-rapp/AndroidPreferenceActivity#15]
Setting up a pretty basic PreferenceActivity with headers that calls a PreferenceFragment.

Activity

```
public class SettingsActivity extends PreferenceActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    protected final void onCreatePreferenceHeaders() {
        addPreferenceHeadersFromResource(R.xml.preference_headers);
    }
}
```

Fragment

```
public class AppearanceFragment extends PreferenceFragment {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addPreferencesFromResource(R.xml.nested_appearance_preferences);
    }

    @Override
    public boolean onPreferenceTreeClick(PreferenceScreen preferenceScreen, Preference preference) {
        return super.onPreferenceTreeClick(preferenceScreen, preference);
    }

    @Override
    public void onPause() {
        super.onPause();
    }
}
```

Header

```
<?xml version="1.0" encoding="utf-8"?>
<preference-headers xmlns:android="http://schemas.android.com/apk/res/android">

    <header
        android:fragment="me.calebjones.spacelaunchnow.settings.AppearanceFragment"
        android:icon="@drawable/ic_settings_black"
        android:title="General"
        android:summary="@string/general_settings_for_launch_tracking_and_application_behavior"
        android:breadCrumbShortTitle="breadCrumbShortTitle"
        android:breadCrumbTitle="breadCrumbTitle" />
    <header
        android:fragment="me.calebjones.spacelaunchnow.settings.AppearanceFragment"
        android:icon="@drawable/ic_notifications"
        android:title="Notifications"
        android:summary="Set up launch notifications and scheduling."/>
    <header
        android:fragment="me.calebjones.spacelaunchnow.settings.AppearanceFragment"
        android:icon="@drawable/ic_color_picker"
        android:title="Appearance"
        android:summary="Customize app theme and colors."/>
    <header
        android:fragment="me.calebjones.spacelaunchnow.settings.AppearanceFragment"
        android:icon="@drawable/ic_wear"
        android:title="Wear"
        android:summary="Change Android Wear watch face settings."/>
    <header
        android:icon="@drawable/ic_about_black"
        android:summary="Application information about license, libraries, changelog, etc"
        android:title="About">
        <intent
            android:targetClass="me.calebjones.spacelaunchnow.ui.activity.AboutActivity"
            android:targetPackage="me.calebjones.spacelaunchnow.ui.activity"/>
    </header>
    <header
        android:icon="@drawable/ic_support_black"
        android:summary="Follow my projects and contribute to future development."
        android:title="Support">
        <intent
            android:targetClass="me.calebjones.spacelaunchnow.supporter.SupporterActivity"
            android:targetPackage="me.calebjones.spacelaunchnow.supporter"/>
    </header>

</preference-headers>
```

And i'm getting this when clicking on an item:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.calebjones.spacelaunchnow.debug, PID: 32224
                  java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                      at android.view.ViewGroup.addViewInner(ViewGroup.java:4454)
                      at android.view.ViewGroup.addView(ViewGroup.java:4295)
                      at android.view.ViewGroup.addView(ViewGroup.java:4252)
                      at de.mrapp.android.preference.activity.PreferenceFragment.initializeListView(PreferenceFragment.java:147)
                      at de.mrapp.android.preference.activity.PreferenceFragment.onCreateView(PreferenceFragment.java:719)
                      at android.app.Fragment.performCreateView(Fragment.java:2352)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                      at android.app.BackStackRecord.run(BackStackRecord.java:815)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                      at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by michael-rapp** [comment]
What Android version are you running?

**Comment by ItsCalebJones** [comment]
Android 7.0, ill see if its reproducible on other devices.

**Comment by michael-rapp** [comment]
I saw this kind of error once before. I suspect it to have something to do with Android 7. I'm on it.

**Comment by ItsCalebJones** [comment]
Awesome, confirmed it is not an issue on 4.0 and 6.0. Thanks for the quick response.

**Comment by ItsCalebJones** [comment]
Unrelated, how can I theme the toolbar? Currently Day theme has dark text when I want it white.

**Comment by michael-rapp** [comment]
What toolbar are you talking about? Please make a screenshot. Maybe post it as a separate issue, so we don't mix things up here.

**Comment by michael-rapp** [comment]
I noticed that the when using the library's light theme, the text color of a `PreferenceActivity`'s toolbar is dark on smartphones. Maybe this is the same issue you encountered. Take a look at this bug report I created : https://github.com/michael-rapp/AndroidPreferenceActivity/issues/16

**Comment by michael-rapp** [comment]
Fixed in version 4.2.5.

**Comment by ItsCalebJones** [comment]
#16 is exactly what I was seeing, thanks for the quick fixes.

**Comment by developweb10** [comment]
Hi @michael-rapp  can you please help me to resolve this issue I got same issue in android N and below android N code is working fine. when i open activity sometime application has been crashed.


                                      java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                          at android.view.ViewGroup.addViewInner(ViewGroup.java:4550)
                                          at android.view.ViewGroup.addView(ViewGroup.java:4391)
                                          at android.view.ViewGroup.addView(ViewGroup.java:4331)
                                          at android.view.ViewGroup.addView(ViewGroup.java:4304)
                                          at com.google.android.apps.gsa.sidekick.shared.overlay.bl.c(SourceFile:8)
                                          at com.google.android.apps.gsa.shared.monet.ac.azU(SourceFile:9)
                                          at com.google.android.apps.gsa.shared.monet.ac.c(SourceFile:6)
                                          at com.google.android.apps.gsa.shared.monet.RendererPublisher.publishRenderer(SourceFile:12)
                                          at com.google.android.apps.gsa.plugins.shortcuts.a.c.ac.a(SourceFile:14)
                                          at com.google.android.libraries.gsa.monet.tools.children.b.c.run(Unknown Source)
                                          at com.google.android.libraries.gsa.monet.tools.children.b.d.onSuccess(SourceFile:2)
                                          at com.google.android.libraries.gsa.monet.tools.a.c.onSuccess(SourceFile:11)
                                          at com.google.common.util.concurrent.az.run(SourceFile:13)
                                          at com.google.common.util.concurrent.br.execute(SourceFile:3)
                                          at com.google.common.util.concurrent.d.b(SourceFile:271)
                                          at com.google.common.util.concurrent.d.addListener(SourceFile:135)
                                          at com.google.common.util.concurrent.ax.a(SourceFile:46)
                                          at com.google.android.libraries.gsa.monet.tools.a.b.a(SourceFile:16)
                                          at com.google.android.libraries.gsa.monet.tools.children.b.e.onModelUpdate(SourceFile:60)
                                          at com.google.android.libraries.gsa.monet.internal.shared.b.bu(SourceFile:28)
                                          at com.google.android.libraries.gsa.monet.internal.b.ap.a(SourceFile:23)
                                          at com.google.android.apps.gsa.shared.monet.h.onServiceEvent(SourceFile:110)
                                          at com.google.android.apps.gsa.search.shared.service.ab.call(SourceFile:7)
                                          at com.google.android.apps.gsa.search.shared.service.aa.run(SourceFile:2)
                                          at android.os.Handler.handleCallback(Handler.java:836)
                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                          at android.os.Looper.loop(Looper.java:203)
                                          at android.app.ActivityThread.main(ActivityThread.java:6339)
                                          at java.lang.reflect.Method.invoke(Native Method)
                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by michael-rapp** [comment]
Is this in any way related to the library "AndroidPreferenceActivity"? I cannot see a connection from the stacktrace.

However, it seems as in line  8 of the class `com.google.android.apps.gsa.sidekick.shared.overlay.bl.c.SourceFile` a view is added to another view although it has already been added somewhere else. From the package name I assume, that this does not happen in your code, but in some Google library. Either you are using it in the wrong way, or there is a bug. I don't have enough information for a deeper analysis.

**Comment by developweb10** [comment]
@michael-rapp thanks for quick reply 


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':library')
    compile 'com.flurgle:camerakit:0.9.17'
    compile 'com.android.support.constraint:constraint-layout:1.0.0'
    compile 'com.jakewharton:butterknife:5.1.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.squareup.picasso:picasso:2.3.2'
    compile 'com.github.bumptech.glide:glide:3.8.0'
    compile 'com.commit451:PhotoView:1.2.4'
    compile project(':collage-views')
    compile 'com.google.android.gms:play-services:11.0.4'
    compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
    compile 'id.zelory:compressor:2.1.0'
    compile 'com.squareup.picasso:picasso:2.3.2'
    compile 'jp.wasabeef:picasso-transformations:2.1.2'
    compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.4.1'
}

I have using above library first time everything is working fine but sometime  when i just closed the MainActivty and re open the app or open Main Activity from other activity then APP become crashed and issue occurred only android N
