### ISSUE TITLE
java.lang.IllegalStateException: Fragment AppearancePreferenceFragment not attached to Activity

### ISSUE THREAD

**Issue by kingdom2011** [michael-rapp/AndroidPreferenceActivity#20]
there is a problem with the restore defaults button. it works for the first time. if you keep pushing restore press ok in the dialog it will crash in both appearance and behavior. you don't need to change any value in preferences just press restore defaults for a few times and hit ok.
the error is different for appearance and behavior. and if you press restore defaults for 2nd time in appearance and press ok. the dialog comes again without needing to press restore this time.
here is the error for behavior:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
                      at de.mrapp.android.preference.activity.example.fragment.BehaviorPreferenceFragment$1.onPreferenceChange(BehaviorPreferenceFragment.java:49)
                      at de.mrapp.android.preference.activity.example.fragment.BehaviorPreferenceFragment.onRestoredDefaultValue(BehaviorPreferenceFragment.java:112)
                      at de.mrapp.android.preference.activity.PreferenceFragment.notifyOnRestoredDefaultValue(PreferenceFragment.java:409)
                      at de.mrapp.android.preference.activity.PreferenceFragment.restoreDefaults(PreferenceFragment.java:316)
                      at de.mrapp.android.preference.activity.PreferenceFragment.restoreDefaults(PreferenceFragment.java:307)
                      at de.mrapp.android.preference.activity.PreferenceFragment.restoreDefaults(PreferenceFragment.java:472)
                      at de.mrapp.android.preference.activity.example.fragment.RestoreDefaultsDialogListener$1.onClick(RestoreDefaultsDialogListener.java:55)
                      at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:173)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```
here is the error for appearance:
```
java.lang.IllegalStateException: Fragment AppearancePreferenceFragment{9424a56} not attached to Activity
                      at android.app.Fragment.getResources(Fragment.java:819)
                      at android.app.Fragment.getString(Fragment.java:841)
                      at de.mrapp.android.preference.activity.example.fragment.AppearancePreferenceFragment.onRestoredDefaultValue(AppearancePreferenceFragment.java:228)
                      at de.mrapp.android.preference.activity.PreferenceFragment.notifyOnRestoredDefaultValue(PreferenceFragment.java:409)
                      at de.mrapp.android.preference.activity.PreferenceFragment.restoreDefaults(PreferenceFragment.java:316)
                      at de.mrapp.android.preference.activity.PreferenceFragment.restoreDefaults(PreferenceFragment.java:307)
                      at de.mrapp.android.preference.activity.PreferenceFragment.restoreDefaults(PreferenceFragment.java:472)
                      at de.mrapp.android.preference.activity.example.fragment.RestoreDefaultsDialogListener$1.onClick(RestoreDefaultsDialogListener.java:55)
                      at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:173)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by michael-rapp** [comment]
I was able to reproduce the error, which is thrown in the "Behavior" fragment. When restoring the default values multiple times in the "Appearance" fragment, I observe a different error than you experienced:

```
android.view.WindowLeaked: Activity de.mrapp.android.preference.activity.example.SettingsActivity has leaked window DecorView@41cc22d[] that was originally added here
                                                                                                 at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
                                                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                                 at android.app.Dialog.show(Dialog.java:316)
                                                                                                 at android.app.AlertDialog$Builder.show(AlertDialog.java:1112)
                                                                                                 at de.mrapp.android.preference.activity.example.fragment.RestoreDefaultsDialogListener.onRestoreDefaultValuesRequested(RestoreDefaultsDialogListener.java:82)
                                                                                                 at de.mrapp.android.preference.activity.PreferenceFragment.notifyOnRestoreDefaultValuesRequested(PreferenceFragment.java:362)
                                                                                                 at de.mrapp.android.preference.activity.PreferenceFragment.access$000(PreferenceFragment.java:64)
                                                                                                 at de.mrapp.android.preference.activity.PreferenceFragment$1.onClick(PreferenceFragment.java:256)
                                                                                                 at android.view.View.performClick(View.java:5610)
                                                                                                 at android.view.View$PerformClick.run(View.java:22260)
                                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

Nevertheless, maybe this corresponds to the same problem you encountered. What Android version do you use? Maybe the error messages differ for different Android releases.

**Comment by michael-rapp** [comment]
I fixed the errors, I was able to reproduce, in version 4.2.10. If you are still encountering any issues feel free to re-open this issue.

**Comment by michael-rapp** [comment]
By the way, these were only problems in the example app. There were no issues in the library itself.
